### ISSUE TITLE
WTF? I encountered a problem and asked for a solution. Did you close my issue?

### ISSUE THREAD

**Issue by allmors** [unjs/httpxy#42]
### Environment

- debian
- nodejs 18

### Reproduction

Use the official tutorial

### Describe the change

```
import { createServer } from "node:http";

import { createProxyServer } from "httpxy";

const proxy = createProxyServer({});

const server = createServer(async (req, res) => {
  try {
    await proxy.web(req, res, {
      target: main.url,
    });
  } catch (error) {
    console.error(error);
    res.statusCode = 500;
    res.end("Proxy error: " + error.toString());
  }
});

server.listen(3000, () => {
  console.log("Proxy is listening on http://localhost:3000");
});
```
The above code runs with an error
![image](https://github.com/unjs/httpxy/assets/93471589/411e18fd-88c1-4b2c-b858-d9aaaa81bc5b)
![image](https://github.com/unjs/httpxy/assets/93471589/c866d7ce-f58e-4ae7-8949-6b59beff665c)

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
1. Learn how to communicate in OSS.
2. Learn about how HTTP and TLS works. You need proper host / headers for proxy to certain hosts
3. Look at the error it tells you something
4. Chat gpt is also your friend
5. If you continue this attitude you will also get banned from this community. Again we are here to collaborate not free support and spend time for someone rude. In fact I already took time to write all these to you.
